# Use postgres/example user/password credentials
version: '3.6'

services:

  web:
    container_name: mytoolbag5.6
    image: atoolbag:5.6 
    env_file:
      - .env
    ports:
      - 8000:8000
# port 8888 jupyter is mapped through reverse proxy: localhost:8000/notebook





