# Use postgres/example user/password credentials
version: '3.6'

services:

  web:
    container_name: mytoolbag5.4
    image: atoolbag:5.4
    env_file:
      - .env
    ports:
      - 8000:8000





