# Use postgres/example user/password credentials
version: '3.6'

services:

  db:
    container_name: db
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: atrium

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 82:8080

  pgweb:
    container_name: pgweb
    image: sosedoff/pgweb
    restart: always
    ports:
      - 83:8081
    links:
      - db  # my database container is called postgres, not db
    environment:
      - DATABASE_URL=postgres://postgres:atrium@db:5432/postgres?sslmode=disable
    depends_on:
      - db

  atoolbag:
    container_name: mytoolbag
    image: kbowerma/atoolbag:latest
    restart: always
    ports:
      - 80:8000
      - 81:8888

  graphql-engine:
    image: hasura/graphql-engine:v1.0.0-debian-10.2-slim.3
    ports:
        - "84:8080"
    depends_on:
        - db
    restart: always
    environment:
        #HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:@postgres:5432/postgres
        HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:atrium@db:5432/postgres
        HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
        HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
        ## uncomment next line to set an admin secret
        # HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey



