# Use postgres/example user/password credentials
version: '3.6'

services:

  web:
    build: 
      context: .
      dockerfile: dev.Dockerfile
    container_name: mytoolbag6
    image: atoolbag:6.0
    env_file:
      - .env
    ports:
      - 8000:8000
# port 8888 jupyter is mapped through reverse proxy: localhost:8000/notebook
    volumes: 
      - ./notebooks:/opt/notebooks
      - ./adocs:/opt/adocs
      - ./server:/opt/server





